### ISSUE TITLE
Adding new collaborators

### ISSUE THREAD

**Issue by fredrikekelund** [simplecrawler/simplecrawler#388]
simplecrawler is fairly mature software, but it does suffer from a pretty slow pace of development that has made certain flaws remain unfixed for a long time. We have had some great PR's to help fix bugs and add new crawler options - proving that there is a community out there that relies on simplecrawler and is prepared to dig through the source code. 

What I would like to do to address the slow pace of development is to invite some new collaborators! Initially, I want to invite @venning, @elxa and @civalin based on their recent and meaningful PR's. If any of you are interested in becoming collaborators, just drop a comment in this issue! 

By extending this invitation in an open forum, I hope that others who are keen in stepping up will get a chance to express their interest, and to make it easy for everyone up to speed with the code base by handling any questions you might have here.

**Comment by fredrikekelund** [comment]
Whoops, looks like @elxa is @konstantinblaesi now!

**Comment by civalin** [comment]
@fredrikekelund Wow, thanks. Really surprised you mentioned me :D

Currently I'm focus on other area and can't afford real-time cooperation, quick communication / response on this project. I think I can not meet your expectations, sorry. But if you don't care those problems, feel free to add me in. Maybe after a while I can think out what can I do in here.

**Comment by konstantinblaesi** [comment]
@fredrikekelund Thanks, I am happy to join since we are extensively using simplecrawler!

**Comment by fredrikekelund** [comment]
@civalin - real time collaboration isn't a requirement, our ambition is to increase the pace of development, but we don't have to match the efforts of paid open source contributors. If and when you feel that you're able to put in the time, let us know :)

@konstantinblaesi - great, happy to hear it! 👍 The fact that you are using simplecrawler in production means a lot too - I also started contributing when simplecrawler was used heavily at my workplace. 

We will add you as a collaborator! It would be good if we could continue to work with PR's instead of pushing directly to master, though. This makes it easier to coordinate changes and gather feedback.

**Comment by konstantinblaesi** [comment]
@fredrikekelund makes sense! Afaik I am not allowed to push to master since you added the review-required constraint recently. I already tried to push this as a quick CI fix #389.

**Comment by fredrikekelund** [comment]
@konstantinblaesi ah, @cgiffard is ahead of me! I'll have a look at #389 as soon as possible. Currently on vacation, but it looks like a small change

**Comment by fredrikekelund** [comment]
Closing this for now. If anyone else is interested in joining - don't hesitate to reach out to @cgiffard, me or @konstantinblaesi! PR's are always welcome, and if you've submitted substantial patch, you're welcome to join as a collaborator as well

**Comment by venning** [comment]
Sorry for the slow response.  I'm not able to contribute to any open source projects right now, aside from drive-by bug fixes, which is what I contributed earlier.

I do appreciate you asking and wish you all the best with *simplecrawler*.  It's really nice and helped me with a project at work.

**Comment by fredrikekelund** [comment]
@venning alright! Happy to hear you found it useful. You're of course welcome to submit other fixes without becoming a collaborator as well, should you ever find the need to do so
