### ISSUE TITLE
Sitemap Parsing Example

### ISSUE THREAD

**Issue by koolma** [simplecrawler/simplecrawler#392]
Hi,
this is more a question rather than an issue:

Does this crawler supports sitemaps referenced in robots.txt-files? Looking up the code I'd say no, but there is a PR that indicates that sitemaps are somewhat supported.

Would anybody be able to link to an example of simplecrawler using a sitemap?

**Comment by fredrikekelund** [comment]
Hi! The crawler's default discovery mechanism is indeed capable of extracting URL's from sitemaps, but I do not believe we queue the URL's to sitemaps referenced in robots.txt's. Seems like a reasonable change, though. We even use a dedicated module for parsing robots.txt's, so it should be a minor change to implement. 

If you would consider making a PR, then that would be welcome - otherwise we will look into it as soon as we get a chance!

**Comment by LeMoussel** [comment]
@fredrikekelund, you say at will make the crawler add sitemap URL's discovered in robots.txt to the queue automatically.  Will this be an option? 
For various reasons,it's interesting to know URL's discovered in robots.txt sitemap discovered in robots.txt sitemap directive but not crawl it.

**Comment by fredrikekelund** [comment]
I would prefer to not make a new option out of it. But you would be able to use fetch conditions to stop sitemap URL's from being queued, and by using `queueadd` events, you could look also see which URL's are added with a `referrerQueueItem` that has a `path` attribute of `/robots.txt`. 

Also, if you set `respectRobotsTxt = false`, then sitemaps won't be automatically added to the queue.

I have not verified that this works, but here's the gist of what I'm imagining:

```js
crawler.on("queueadd", function(queueItem, referrerQueueItem) {
    if (referrerQueueItem.path === "/robots.txt") {
        console.log("This is a sitemap URL:", queueItem.url);
    }
});
```

PS. I see that the `referrerQueueItem` parameter to the `queueadd` event isn't in fact documented in the README – I'll make sure to fix that.

**Comment by LeMoussel** [comment]
is it OK to stop sitemap URL's from being queued, I do that 
```
crawler.addFetchCondition(function(queueItem, referrerQueueItem, callback) {
        callback(null, !referrerQueueItem.path === "/robots.txt");
});
```

and good idea to document `referrerQueueItem` parameter :)
