### ISSUE TITLE
Cookies not passed properly during crawl.

### ISSUE THREAD

**Issue by HaroldPutman** [simplecrawler/simplecrawler#397]
## What happened?
Cookies set before crawling are not sent properly to the host. 
* Extra data is being sent in the outbound Cookie header. (domain, path, etc.. should not be included)
* Node 7 and lower separates multiple cookies with comma instead of semicolon.

## What should have happened?
The cookies should reach host correctly. Node version 8 does a better job with multiple cookies, but still there is extraneous data being sent.

## Steps to reproduce the problem
Here is a [code sample](https://github.com/HaroldPutman/simplecrawler-cookie-probs.git) demonstrating the issue.

**Comment by fredrikekelund** [comment]
Thanks for looking into this, @HaroldPutman! Will get a bug fix release with your PR included out in a minute
