### ISSUE TITLE
robots.txt Error: socket hang up & no link discovery

### ISSUE THREAD

**Issue by LeMoussel** [simplecrawler/simplecrawler#403]
I'm trying to crawl https://www.groupama.fr/ but your crawler wasn't able to crawl it.
The event triggered was "robotstxterror" but the robots.txt file is OK (status code 200 and valid robots).
I tried to crawl ignoring robots using `respectRobotsTxt=false` but the crawler do nothing, No link is  discovery.

if i set `respectRobotsTxt=true` the crawler trigger the event 'robotstxterror' but with this error:
```
=> robots.txt Error:  { Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1130:19)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at TLSSocket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ECONNRESET',
  path: null,
  host: 'www.groupama.fr',
  port: 443,
  localAddress: undefined }
```
```

const Crawler = require("simplecrawler");

let crawler = (new Crawler("https://www.groupama.fr/"))
    .on("fetchcomplete", function () {
        console.log("Fetched a resource!");
    })
    .on("robotstxterror", function(error) {
        console.log("=> robots.txt Error: ", error);
    })
    .on("fetch404", function (queueItem, responseBuffer) {
        console.log("404:", queueItem.url);
    })
    .on("fetcherror", function (queueItem, responseBuffer) {
        console.log("Error:", queueItem.url);
    })
    .on("fetchtimeout", function (queueItem, timeoutVal) {
        console.log("Timeout:", queueItem.url);
    });

crawler.maxDepth = 2;
//crawler.respectRobotsTxt = false;
crawler.start();
```

**Comment by konstantinblaesi** [comment]
The server's TLS protocol  version and ciphers are very outdated and insecure. When a client connects to a server, they will exchange information about supported TLS protocol versions and ciphers. If no suitable match is found, the connection is terminated. The reason you cannot crawl this page is that Node.js (by default) refuses to connect to these insecure servers.
Here is a report for the SSL/TLS status of this page: https://www.ssllabs.com/ssltest/analyze.html?d=www.groupama.fr

There is a workaround described at https://nodejs.org/api/tls.html#tls_modifying_the_default_tls_cipher_suite to change/weaken the cipher suite.
If you run your crawler with
```node --tls-cipher-list="DES-CBC3-SHA" main.js```
(assuming your entry file is main.js), it'll work.

**Comment by LeMoussel** [comment]
Thank you very much for your help, I did not know these aspects of outdated and insecure protocol. 
And congratulations for `simplecrawler`. It's a very interesting tool.
