### ISSUE TITLE
Uncaught TypeError: Cannot read property 'maxSockets' of undefined

### ISSUE THREAD

**Issue by praneethmendu** [simplecrawler/simplecrawler#404]
I trying to get the html of a simple single url [https://etherscan.io/txsPending](https://etherscan.io/txsPending) and the following is all the js there is in the project : 

	var Crawler = require("simplecrawler");
	var crawler = Crawler("https://etherscan.io/txsPending/")

	crawler.interval = 7000; // Ten secondss
	crawler.respectRobotsTxt=false
	crawler.on("fetchcomplete", function(queueItem, responseBuffer, response) {
		console.log("I just received %s (%d bytes)", queueItem.url, responseBuffer.length);
		console.log("It was a resource of type %s", response.headers['content-type']);
	});

	crawler.start();

I installed simplecrawler with npm. Then ran a simple webpack. When I run the page in a browser I get : 

	bundle.js:17948 Uncaught TypeError: Cannot read property 'maxSockets' of undefined
	at bundle.js:17948
	at FetchQueue.update (bundle.js:9991)
	at Crawler.fetchQueueItem (bundle.js:17938)
	at bundle.js:18561
	at FetchQueue.oldestUnfetchedItem (bundle.js:10012)
	at Crawler.crawl (bundle.js:18513)
	at bundle.js:17232
	at Item.run (bundle.js:5550)
	at drainQueue (bundle.js:5520)

code in bundle.js where it fails:

	if (agent.maxSockets < crawler.maxConcurrency) {
		agent.maxSockets = crawler.maxConcurrency;
	}

complete minimal code hosted at https://github.com/praneethmendu/bruteapi

windows 10
node v8.5.0
npm 5.3.0
webpack 3.6.0
simplecrawler@1.1.5

**Comment by konstantinblaesi** [comment]
Simply run your crawler with `node entry.js`. While Node.js uses JavaScript as it's language, that does not mean you can run it in a browser. Webpack is used to develop/package website assets afaik. I don't think it has a purpose in the Node.js ecosystem.

**Comment by praneethmendu** [comment]
Im quiet new to JS. Thanks for taking the time to teach me
