### ISSUE TITLE
How can I get sitemap URLs?

### ISSUE THREAD

**Issue by LeMoussel** [simplecrawler/simplecrawler#405]
Hi,

On start of crawl, I need to test if `sitemap` directive is present in robots.txt file. 
robots-parser module has [getSitemaps()](https://github.com/samclarke/robots-parser#getsitemaps) who returns an array of sitemap URLs specified by the sitemap directive.

I find nothing with simplecrawler on how can I get sitemap URLs, Is it possible to do that?

**Comment by LeMoussel** [comment]
Here's my solution
```
// Fired when the crawler completes processing all the items in its queue, and does not find any more to add. 
crawler.on("complete", function() {
    let sitemapUrl = "";
    try { 
        sitemapUrl = this._robotsTxts.reduce(function(result, robots) {
            return robots.getSitemaps();
        }, undefined);
    } catch (error) { }    
    if (sitemapUrl !== undefined && sitemapUrl.length > 0) {
        loggerConsole.info("robots.txt, Sitemap directive: %s ", sitemapUrl);
    }
});
```

**Comment by fredrikekelund** [comment]
Happy to hear you were able to resolve this, @LeMoussel! It looks like your use case was pretty specific, but there's a patch coming this week as well that will make the crawler add sitemap URL's discovered in robots.txt to the queue automatically. Keep an eye out in #392
