### ISSUE TITLE
How to extract canonical URL from HTML Source?

### ISSUE THREAD

**Issue by LeMoussel** [simplecrawler/simplecrawler#408]
Due to duplicate content issues some sites use canonical tag in HTML source.
I would like to extract the "canonical" URL for HTML pages based on the header tag. 
It looks like this:
`<link rel="canonical" href="http://www.example.com/page" />`

I'm not good in regex, but I think I can extract tag with regexp like this 
`^.*canonical.*(http\:|https\:).*$`
and  then use this in another "match text" to get the URL:
`(?<=(href[:space:]?=[:space:]?['"]))[^"']*`

But I'm not sure and I don't know how to integrate regex with simplecrawler

**Comment by konstantinblaesi** [comment]
Use [Cheerio](https://cheerio.js.org/)

**Comment by fredrikekelund** [comment]
As @konstantinblaesi mentioned – cheerio is a good library for constructing and querying a DOM of the HTML document at hand (it uses an API modelled after jQuery). You want to be interacting with pages in the `fetchcomplete` event.

You want something like this:

```js
crawler.on("fetchcomplete", function(queueItem, responseBody, response) {
    var $ = cheerio.load(responseBody);
    var canonicalTag = $('link[rel="canonical"]');
    canonicalTag.attr('href');
});
```

**Comment by LeMoussel** [comment]
OK but why is Cheerio not used with `simplecrawler`?

**Comment by konstantinblaesi** [comment]
My guess is that the devs wanted to limit the scope of the core simplecrawler to not do any content extraction/manipulation. This functionality can be easily added as modules listening on simplecrawlers events.

**Comment by LeMoussel** [comment]
Wel, well, OK but I'm only moderately convinced. 
`simplecrawler`  uses some of regular expressions for discover resources ([discoverRegex](https://github.com/simplecrawler/simplecrawler/blob/master/lib/crawler.js#L323)),  he could use Cheerio instead.

**Comment by fredrikekelund** [comment]
The Crawler#discoverResources method is meant to be easy to override. A common use case is to override the default method and use cheerio instead. There has been talk of replacing the current method with a cheerio solution, but it has never been very highly prioritized. 

I also want to point out that simplecrawler is a library, not a ready made solution for crawling any website - its object orientated nature and event driven API is there to make it easy to extend. We want it to make the right choices by default, but we don't want to integrate too many specific use cases, because that makes for a bad API and hard to maintain software.

**Comment by LeMoussel** [comment]
OK. I propose to close this this issue.

**Comment by timofeycom** [comment]
To anyone else looking for a good template for link parsing, here's the solution I'm using. The code is inspired by https://github.com/brendonboshell/supercrawler/blob/master/lib/handlers/htmlLinkParser.js:

```node
    crawler.on("fetchcomplete", function(queueItem, responseBuffer, response) {

        // Link Discovery code is borrowed from htmlLinkParser in SuperCrawler
        crawler.discoverResources = function(buffer, queueItem) {
            var $ = cheerio.load(buffer.toString("utf8"));

            return $("a[href], link[href][rel=alternate], area[href], link[href]").map(function () {
                var $this,
                    targetHref,
                    absoluteTargetUrl,
                    urlObj,
                    protocol,
                    hostname;

                $this = $(this);
                targetHref = $this.attr("href");
                // Turns relative URLS into absolute
                absoluteTargetUrl = url.resolve(queueItem.url, targetHref);
                urlObj = url.parse(absoluteTargetUrl);
                protocol = urlObj.protocol;
                hostname = urlObj.hostname;

                if (protocol !== "http:" && protocol !== "https:") {
                    return null;
                }

                // Restrict links to current hostname
                if (queueItem.host.indexOf(hostname) === -1) {
                    return null;
                }

                return url.format({
                    protocol: urlObj.protocol,
                    auth: urlObj.auth,
                    host: urlObj.host,
                    pathname: urlObj.pathname,
                    search: urlObj.search
                });
            }).get();
        };
    });
```
