### ISSUE TITLE
Please help to Answer Question on Stackoverflow

### ISSUE THREAD

**Issue by coommark** [simplecrawler/simplecrawler#426]
I asked a question on Stackoverflow [here](https://stackoverflow.com/questions/50218402/nodejs-web-crawling-with-node-crawler-or-simplecrawler) 

My aim is to crawl a website and obtain ONLY the internal (local) URLs within that domain. I am not interested in any page data or scraping. Just the URLs.

Kindly help me and respond to the question. Thank you in advance!

**Comment by tlhunter** [comment]
This will only download one page, and then fire an event when the links are discovered:

```js
  crawler.maxDepth = 1;
  crawler.on('discoverycomplete', (item, links) => { void links; });
```

You'd then iterate `links`, throw them into `url.parse`, and make sure the hostname matches your original domain name.

**Comment by fredrikekelund** [comment]
simplecrawler will by default only crawl URLs that match the domain that the crawler starts at. I posted an answer to your question on StackOverflow as well @coommark
