### ISSUE TITLE
Multiple hosts

### ISSUE THREAD

**Issue by mdalmazzi** [simplecrawler/simplecrawler#427]
HI,

how can I crawler different hosts without creating different crawler instances?

Thanks M.

**Comment by haganbt** [comment]
Im curious about this also. I have attempted to create multiple instances however cannot see a way to kill and instance after a successful crawl.

Appreciate any guidance.

**Comment by davidspiess** [comment]
I used 

```js
  const crawler = new Crawler("https://www.domain1.com");
  crawler.queueURL("https://www.domain2.com");
```

I'm also concerned about the crawler hanging, so i implemented a timeout function which stops it after 15 min.

```js
  // Add a time limit for maximal execution
  const timeout = setTimeout(function() {
    crawler.stop();
    clearTimeout(timeout);
    console.warn(`Crawl for ${site.domain} timed out and was aborted!`);
    callback(count);
  }, 900000); // 15 minutes
```

**Comment by fredrikekelund** [comment]
Hi everyone! Seems like there are two different things that you folks are trying to accomplish. 

If you're trying to crawl multiple domains with one crawler instance, have a look at the `crawler.domainWhitelist` setting. 

If you're trying to launch multiple crawler instances, then there's no one true way, but I have in the past built a system where a mother process would spawn child processes and each one crawler a different domain.

I'll close this for now, but let me know if you continue having trouble @mdalmazzi
