### ISSUE TITLE
Uncaught TypeError - invalid input

### ISSUE THREAD

**Issue by karimation** [simplecrawler/simplecrawler#433]
Hi,

I'm getting the following messages when i try to launch my app with simplecrawler package:

![capture du 2018-06-16 04-36-14](https://user-images.githubusercontent.com/21101482/41495424-d4286862-711e-11e8-8635-719fac31cefb.png)

i have tried other version but nothing change.

**Comment by fredrikekelund** [comment]
Hi there! Could you post your code here as well, so I can have a look?

**Comment by karimation** [comment]
Hi,
i just used the code exists in the documentation.

**Comment by fredrikekelund** [comment]
Would you mind still just copying+pasting the code in here?

**Comment by karimation** [comment]
i just started with this code: 
```
var Crawler = require("simplecrawler");
var moment = require("moment");
var cheerio = require("cheerio");

var crawler = new Crawler("http://example.com");

function log() {
    var time = moment().format("HH:mm:ss");
    var args = Array.from(arguments);

    args.unshift(time);
    console.log.apply(console, args);
}

crawler.downloadUnsupported = false;
crawler.decodeResponses = true;

crawler.addFetchCondition(function(queueItem) {
    return !queueItem.path.match(/\.(zip|jpe?g|png|mp4|gif)$/i);
});

crawler.on("crawlstart", function() {
    log("crawlstart");
});

crawler.on("fetchcomplete", function(queueItem, responseBuffer) {
    log("fetchcomplete", queueItem.url);
});

crawler.on("fetch404", function(queueItem, response) {
    log("fetch404", queueItem.url, response.statusCode);
});

crawler.on("fetcherror", function(queueItem, response) {
    log("fetcherror", queueItem.url, response.statusCode);
});

crawler.on("complete", function() {
    log("complete");
});

crawler.start();
```

**Comment by fredrikekelund** [comment]
Did you encounter the error running exatly that code then? Does the error appear when you run it against http://example.com?

For me, that code actually runs fine. But looking at the stack trace you posted, it looks like it could be an issue with a particular URL being added to the queue that's not actually valid.

**Comment by konstantinblaesi** [comment]
@karimation I'd change https://github.wdf.sap.corp/srch-hana-core/simplecrawler/blob/master/lib/crawler.js#L1859 in `node_modules/simplecrawler/lib/crawler.js` from
```
var url = uri(queueItem.url).normalize();
var host = uri({
    protocol: url.protocol(),
    hostname: url.hostname(),
    port: url.port()
}).href();
```
to
```
var url = uri(queueItem.url).normalize();
try {
    var host = uri({
        protocol: url.protocol(),
        hostname: url.hostname(),
        port: url.port()
    }).href();
} catch (error) {
    console.dir(url, {depth:null});
    throw error;
}
```

To get more information on the specific url that simplecrawler/uri.js cannot handle. This is a bug in simplecrawler, because the urijs error isn't handled.

**Comment by karimation** [comment]
@konstantinblaesi that's  helpful. thank you ;)
