### ISSUE TITLE
Does simplecrawler support distributed queuing?

### ISSUE THREAD

**Issue by myrtleTree33** [simplecrawler/simplecrawler#437]
Hello!

I'm wondering if it is possible to run simplecrawler as a distributed cache, to reduce download time?

That means to manually inject and retrieve items from a distributed queue, e.g. Redis.  I am just wondering if this is the right way to proceed?

**Comment by fredrikekelund** [comment]
This has been a long-standing ambition - to be able to run multiple crawler instances that share a queue that's backed by Redid, for instance. The architecture should support it, but you will need to write a queue implementation that uses Redis (or something similar) yourself.

One alternative might be too look into https://github.com/yujiosaka/headless-chrome-crawler - they support distributed crawling if I'm not mistaken
