### ISSUE TITLE
Cannot find site page

### ISSUE THREAD

**Issue by GameRussia** [simplecrawler/simplecrawler#471]
Crawler returns only the main page of the site **svalka58.ru** and a Sitemap.xml. He doesn't find any more pages. Why?

**Comment by kbychkov** [comment]
@GameRussia, show your code please

**Comment by GameRussia** [comment]
`var options = {
                stripQuerystring: false,
                userAgent: 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36',
                maxResourceSize: 67108864
              }

              const Crawler = require('simplecrawler');
			  const has = require('lodash/has');

			  const discoverResources = require('./discoverResources');
			  const stringifyURL = require('./stringifyURL');
			  const normalizeUrl = require('normalize-url');
			  const parseURL = require('url-parse');
			  var uri = parseURL(
			    normalizeUrl(url, {
			      stripWWW: false,
			      removeTrailingSlash: false
			    })
			  )
				  // excluded filetypes
			  const exclude = [
			    'gif',
			    'jpg',
			    'jpeg',
			    'png',
			    'ico',
			    'bmp',
			    'ogg',
			    'webp',
			    'mp4',
			    'webm',
			    'mp3',
			    'ttf',
			    'woff',
			    'json',
			    'rss',
			    'atom',
			    'gz',
			    'zip',
			    'rar',
			    '7z',
			    'css',
			    'js',
			    'gzip',
			    'exe',
			    'svg'
			  ].join('|');

			  const extRegex = new RegExp(`\\.(${exclude})$`, 'i');

			  const crawler = new Crawler(uri.href);

			  Object.keys(options).forEach(o => {
			    if (has(crawler, o)) {
			      crawler[o] = options[o];
			    } else if (o === 'crawlerMaxDepth') {
			      // eslint-disable-next-line
			      console.warn(
			        'Option "crawlerMaxDepth" is deprecated. Please use "maxDepth".'
			      );
			      if (!options.maxDepth) {
			        crawler.maxDepth = options.crawlerMaxDepth;
			      }
			    }
			  });

			  // use custom discoverResources function
			  crawler.discoverResources = discoverResources;

			  // set crawler options
			  // see https://github.com/cgiffard/node-simplecrawler#configuration
			  crawler.initialPath = uri.pathname !== '' ? uri.pathname : '/';
			  crawler.initialProtocol = uri.protocol.replace(':', '');

			  // restrict to subpages if path is provided
			  crawler.addFetchCondition(parsedUrl => {
			    const initialURLRegex = new RegExp(`${uri.pathname}.*`);
			    return stringifyURL(parsedUrl).match(initialURLRegex);
			  });

			  // file type exclusion
			  crawler.addFetchCondition(parsedUrl => !parsedUrl.path.match(extRegex));

			  crawler.start()

			  crawler.on('fetchcomplete', (queueItem, page) => {
			    const { url, depth } = queueItem;
			    console.log(url); // svalka58.ru and svalka58.ru/sitemap.xml
			  });`

**discoverResources**
   `const url = require('url');
    const cheerio = require('cheerio');

    module.exports = (buffer, queueItem) => {
    const $ = cheerio.load(buffer.toString('utf8'));

    const metaRobots = $('meta[name="robots"]');

    if (metaRobots.length && /nofollow/i.test(metaRobots.attr('content'))) {
        return [];
    }

    const links = $('a[href]').map(function iteratee() {
    let href = $(this).attr('href');
    // exclude "mailto:" etc
    if (/^[a-z]+:(?!\/\/)/i.test(href)) {
      return null;
    }

    // exclude rel="nofollow" links
    const rel = $(this).attr('rel');
    if (/nofollow/i.test(rel)) {
      return null;
    }

    // remove anchors
    href = href.replace(/(#.*)$/, '');
    
    //remove basic authentication
    href = href.replace(/^\/?([^/]*@)/, '');

    // handle "//"
    if (/^\/\//.test(href)) {
      return `${queueItem.protocol}:${href}`;
    }

    // check if link is relative
    // (does not start with "http(s)" or "//")
    if (!/^https?:\/\//.test(href)) {
      const base = $('base').first();
      if (base.length) {
        // base tag is set, prepend it
        if (base.attr('href') !== undefined) {
          // base tags sometimes don't define href, they sometimes they only set target="_top", target="_blank"
          href = url.resolve(base.attr('href'), href);
        }
      }

      // handle links such as "./foo", "../foo", "/foo"
      if (/^\.\.?\/.*/.test(href) || /^\/[^/].*/.test(href)) {
        href = url.resolve(queueItem.url, href);
      }
    }

    return href;
  });

  return links.get();
    };
`

**Comment by GameRussia** [comment]
_Только что заметил, что если убрать условия, всё начинает работать как надо_
Just noticed that if you remove the conditions

                         `// use custom discoverResources function
			  // crawler.discoverResources = discoverResources;

			  // set crawler options
			  // see https://github.com/cgiffard/node-simplecrawler#configuration
			  crawler.initialPath = uri.pathname !== '' ? uri.pathname : '/';
			  crawler.initialProtocol = uri.protocol.replace(':', '');

			  // restrict to subpages if path is provided
			  // crawler.addFetchCondition(parsedUrl => {
			  //   const initialURLRegex = new RegExp(`${uri.pathname}.*`);
			  //   return stringifyURL(parsedUrl).match(initialURLRegex);
			  // });

			  // file type exclusion
			  // crawler.addFetchCondition(parsedUrl => !parsedUrl.path.match(extRegex));

			  crawler.start()

			  crawler.on('fetchcomplete', (queueItem, page) => {
			    const { url, depth } = queueItem;
			    console.log(url);
			  });


			  crawler.on('complete', () => {
			  	console.log('complete');
			  })`
everything starts to work as it should

**Comment by GameRussia** [comment]
_Методом исключения понял, что проблема в discoverResources_
By process of elimination realized that the problem is discoverResources

**Comment by GameRussia** [comment]
_Всё заработало, после того, как добавил в discoverResources_
Everything worked after added to discoverResources
`href = href.replace(/PHPSESSID=(.*)?(:;|\r\n)?/, '');`
