### ISSUE TITLE
Which method to use avoid crawling URL's that end with .js /.css /.png/.jpg

### ISSUE THREAD

**Issue by 1997-10** [simplecrawler/simplecrawler#479]
While using this crawler , it is crawling url's that ends with .png ; .jpg ; .js ; .css etc.
But I only want proper URLs that end with '.html'. Which method I can use. Please suggest.

**Comment by kbychkov** [comment]
Hi! The [fetch conditions](https://github.com/simplecrawler/simplecrawler#fetch-conditions) are exactly for your case. Also you can write your own [discroverResources](https://github.com/simplecrawler/simplecrawler#link-discovery) implementation.
